--
-- PostgreSQL database dump
--

\restrict UcpzGHzjjVh41fL8WBCo2pJJYMzlwNrAEYw8sxe6OtYsvYjLp8qdNqa8sjWx4yc

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Students; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public."Students" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Age" integer NOT NULL
);


ALTER TABLE public."Students" OWNER TO app_user;

--
-- Name: Students_Id_seq; Type: SEQUENCE; Schema: public; Owner: app_user
--

ALTER TABLE public."Students" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Students_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Students; Type: TABLE DATA; Schema: public; Owner: app_user
--

COPY public."Students" ("Id", "Name", "Age") FROM stdin;
1	string	0
2	string	0
3	string	0
4	string	0
\.


--
-- Name: Students_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: app_user
--

SELECT pg_catalog.setval('public."Students_Id_seq"', 4, true);


--
-- Name: Students PK_Students; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public."Students"
    ADD CONSTRAINT "PK_Students" PRIMARY KEY ("Id");


--
-- PostgreSQL database dump complete
--

\unrestrict UcpzGHzjjVh41fL8WBCo2pJJYMzlwNrAEYw8sxe6OtYsvYjLp8qdNqa8sjWx4yc

