apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Muhi94/manifest.git
  # Dein GitHub Personal Access Token (PAT) oder Passwort
  password: "REMOVED_FOR_SECURITY"
  # Dein GitHub Username
  username: "Muhi94"
