apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  labels:
    environment: infrastructure
    managed-by: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Muhi94/manifest.git
    targetRevision: HEAD
    path: k8s/sealed-secrets
    directory:
      include: 'controller-standalone.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
